export enum UserRole {
  CITIZEN = 'CITIZEN',
  POLICYMAKER = 'POLICYMAKER',
  DISTRICT_OFFICER = 'DISTRICT_OFFICER',
  STATE_ADMIN = 'STATE_ADMIN',
  DEPARTMENT_OFFICER = 'DEPARTMENT_OFFICER',
  ANALYST = 'ANALYST',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
